_target_: src.trainer.baseline_trainer.SklearnTrainer

cv:
  _target_: src.utils.srm_utils.RunKFold
  n_splits: 5

#default_root_dir: ${paths.output_dir}
#
#min_epochs: 1 # prevents early stopping
#max_epochs: 10
#
#accelerator: cpu
#devices: 1
#
##mixed precision for extra speed-up
#precision: 16

