hyperparam_opt:
  class: sklearn.model_selection.GridSearchCV
  params:
    param_grid:
      AverageVariance__excllev: [ 1.2, 1.5, 1.8 ]
  scoring:
    f1_weighted
  cv:
    _target_: sklearn.model_selection.KFold
    n_splits: 5
    shuffle: False
