hyperparam_opt:
  class: sklearn.model_selection.GridSearchCV
  params:
    param_grid:
      csp__n_cmps: [ 4, 6, 8 ]
      csp__excllev: [ 1.2, 1.5, 1.8 ]
      csp__estimator: [ "scm", "lwf"]
  scoring: f1_weighted
  cv:
    _target_: sklearn.model_selection.StratifiedKFold
    n_splits: 5
    shuffle: False