hyperparam_opt:
  class: sklearn.model_selection.GridSearchCV
  params:
    param_grid:
      averagevariance__excllev: [ 1.2, 1.5, 1.8 ]
      averagevariance__estimator: [ 'lwf', 'scm' ]
  scoring: f1_weighted
  cv:
    _target_: sklearn.model_selection.KFold
    n_splits: 10
    shuffle: True
#  n_jobs: 4