hyperparam_opt:
  class: sklearn.model_selection.GridSearchCV
  params:
    param_grid:
      averagevariance__excllev: [ null, 1.8, 4, 10, 20, 100 ]
      averagevariance__estimator: [ 'lwf', 'scm' ]
  scoring: f1_weighted
  cv:
    _target_: sklearn.model_selection.StratifiedKFold
    n_splits: 5
    shuffle: False

