# Hydra config file for the csp classifier steps
#StepName:
#    _target_: <class to instantiate the step>
#    param1: <step's first parameter>
#    param2: <step's second parameter, etc.>

_target_: src.models.baseline_models.classifier_pipeline
steps_config: # use yaml list syntax to preserve to order
  FeatureExtraction:
    CSP:
      applied: True
      n_cmps: 4
      excllev: 1.8
      estimator: 'scm'
  Transformation:
    var:
      applied: True
      axis: 2
    log:
      applied: True
  Classification:
    LDA:
      applied: True
      solver: 'svd'

#  - CSP:
#      _target_: bbcpy.functions.spatial.CSP
#      scoring:
#        _partial_: true
#        _target_: bbcpy.functions.helpers.evscoring_EV
#      select:
#        _partial_: true
#        _target_: bbcpy.functions.helpers.evselect_best_csp
#  - var:
#      _target_: bbcpy.functions.base.ImportFunc
#      func: numpy.var
#      axis: 2
#  - log:
#      _target_: bbcpy.functions.base.ImportFunc
#      func: numpy.log
#  - LDA:
#      _target_: sklearn.discriminant_analysis.LinearDiscriminantAnalysis