_target_: src.trainer.dnn_trainer.DnnLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: true

plots_settings:
  # plots each n epochs
  plot_every_n_epoch: 10

net:
  _target_: src.models.components.EEG-Conformer.Conformer
  emb_kernel_size_1: [1,25]
  emb_kernel_size_2: [22,1]
  emb_size: 40
  depth: 3
  n_classes: 2