_target_: src.models.eegnet_module.EEGNetLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: true

net:
  _target_: src.models.components.EEG-Conformer.Conformer
  emb_size: 40
  emb_kernel_size_1:
    - 1
    - 22
  emb_kernel_size_2:
    - 5
    - 1

  depth: 3
  n_classes: 2