_target_: src.trainer.dnn_trainer.DnnLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: true


plots_settings:
  plot_every_n_epoch: 5 # plot every n epochs

net:
  _target_: torcheeg.models.cnn.EEGNet
  chunk_size: 9000
  num_electrodes: 62
  dropout: 0.5
  kernel_1: 1024
  kernel_2: 256
  F1: 8
  F2: 16
  D: 2
  num_classes: 2
