_target_: src.models.baseline_models.classifier_pipeline
steps_config: # use yaml list syntax to preserve to order
  FeatureExtraction:
    AverageVariance:
      applied: True
      excllev: 1.8
      estimator: 'lwf'
    Covariance:
      applied: True
      estimator: 'lwf'
  Transformation:
    tangent_space:
      applied: True
  Classification:
    SVC-sklearn:
      applied: True
      class_weight: None