_target_: src.trainer.dnn_trainer.DnnLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: true

plots_settings:
  # plots each n epochs
  plot_every_n_epoch: 10

net:
  _target_: torcheeg.models.cnn.TSCeption
  num_classes: 4
  num_electrodes: 54
  sampling_rate: 1000
  num_T: 15
  num_S: 15
  hid_channels: 32
  dropout: 0.5