mlflow:
  experiment_name: Debug
  run_name: RUN-00
  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: ${paths.log_dir}
  # run_id: ""
