mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  tracking_uri: ${paths.log_dir}/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  prefix: ""
  artifact_location: null
