mlflow:
  experiment_name: Test
  run_name: Debug
  tracking_uri: ${paths.log_dir}/mlflow/mlruns
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: ${paths.log_dir}
  # run_id: ""
