mlflow:
  experiment_name: Debug
  run_name: RUN-00
  tracking_uri: mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  prefix: ""
#  artifact_location: ${mlflow.tracking_uri}/${mlflow.experiment_name}
