mlflow:
  experiment_name: Test
  run_name: Debug
  #  tracking_uri: ${paths.log_dir}\mlflow\mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tracking_uri: ${paths.log_dir}mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: null
  # run_id: ""