mlflow:
  experiment_name: "baseline_classifiers"
  run_name: "csp"
  tracking_uri: ${paths.log_dir}\mlflow\mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: ["alpha_band"]
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: ${paths.log_dir}\mlflow\mlruns
  # run_id: ""
