# https://mlflow.org
mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  experiment_name: "lightning-exp"
  run_name: "eegnet"
#  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tracking_uri: file:///${paths.log_dir}/mlflow/mlruns
  tags: null
  prefix: ""
  artifact_location: null
  # run_id: ""
  # save_dir: "./mlruns"
