# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: srm_eeg.yaml
  - model: baseline_riemann.yaml
  - callbacks: none.yaml
  - logger: mlflow.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: sklearn.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: baseline_riemann.yaml

  # config for hyperparameter optimization
#  - hparams_search: cv_gridsearch_csp.yaml
  - hparams_search: null
#  - hparams_search: sklearn_optuna.yaml

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: default_baseline.yaml

# task name, determines output directory path
# list of tasks [train, test, hparams_search]

task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: [ "baseline" ]

# set False to skip model training
train: True

# set False to skip hyperparameter optimization
tune: False

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42
