# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - override /model: riemann_clf.yaml
  - override /hparams_search: cv_gridsearch_riemann.yaml


# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one


# disable callbacks and loggers during debugging
callbacks: null
logger:
  mlflow:
    experiment_name: DEBUG

extras:
  ignore_warnings: False
  enforce_tags: False

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # use this to also set hydra loggers to 'DEBUG'
  verbose: True

trainer:
  cv:
    n_splits: 2 # debuggers don't like cross-validation
    shuffle: False # debuggers don't like cross-validation

#  accelerator: cpu # debuggers don't like gpus
#  devices: 1 # debuggers don't like multiprocessing
#  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

data:
  chans: [ 'C?,~*3,~*4', 'FC*,~*3,~*4' ]
  classes:
    - "R"
    - "L"
  train_subjects_sessions_dict:
    S1:
      - 2
#  num_workers: 0 # debuggers don't like multiprocessing
#  pin_memory: False # disable gpu memory pin
