# @package _global_

# overwrite task name so debugging logs are stored in separate folder
task_name: "debug-win"

defaults:
  - override /trainer: sklearn.yaml
#  - override /model: riemann_tangent_clf.yaml
#  - override /hparams_search: hpo_riemann_tangent.yaml
#  - override /model: riemann_clf.yaml
#  - override /hparams_search: hpo_riemann.yaml
#  - override /model: mbcsp_clf.yaml
#  - override /hparams_search: hpo_mbcsp.yaml
  - override /model: csp_clf.yaml
  - override /hparams_search: hpo_csp.yaml


tune: False
train: True

paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  data_dir: D:\SMR\
  log_dir: ${oc.env:PROJECT_ROOT}\logs
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}

# disable callbacks and loggers during debugging
callbacks: null
logger:
  mlflow:
    #    experiment_name: DEBUG-HPO
    experiment_name: DEBUG-TRAIN
#    run_name: riemann_tangent
#    run_name: riemann
    run_name: csp
#    run_name: mbcsp
    tracking_uri: ${paths.log_dir}\mlflow\mlruns

data:
  task_name: "2D"
  ival: 2s:10s:10ms
  chans: [ "*" ]
#  bands: [ [ 8, 13 ], [ 21, 26 ], [ 31.5, 39 ] ]
  bands: [ 8, 13 ]
  subject_sessions_dict:
    S3: "all"
  loading_data_mode: "within_subject"
  normalize: { norm_type: "std", norm_axis: 0 }
  transform: None

trainer:
  train_val_split: { val_size: 0.1, random_seed: 1234 }
  cv:
    _target_: sklearn.model_selection.KFold
    n_splits: 2
    shuffle: True

extras:
  ignore_warnings: False
  enforce_tags: False

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # use this to also set hydra loggers to 'DEBUG'
  verbose: True


